### ISSUE TITLE
Feature request: Joystick and rubber keyboard support

### ISSUE THREAD

**Issue by stefanbylund** [StalePixels/SPUI#2]
Add the ability to control the menu selection bar via keys 6 and 7 for moving down and up and key 0 for selection. Then the menu can be controlled via a joystick and a rubber keyboard without using Caps Shift.

**Comment by Xalior** [comment]
Thanks for transcribing these over, @stefanbylund - we'll get them folded in before the next release!

-Dx

**Comment by Xalior** [comment]
Added in release v0.4.1
